#ifndef SERVERPROVIDERINIT_H
#define SERVERPROVIDERINIT_H

#include "ServerProvider.h"

#ifdef ARDUINO
#include <Arduino.h>
#include "HttpTcpArduinoServer.h"
#else
#include <iostream>
#endif

/**
 * Initialize the provider with default server types
 * Registers HttpTcpArduinoServer for Arduino builds
 * @return true if initialization was successful, false if server already registered
 */
inline Bool Init() {
#ifdef ARDUINO
    Serial.println("[ServerProviderInit] Init() called");
    
    // Register HttpTcpArduinoServer with ID "arduinotcpserver"
    StdString serverId = "arduinotcpserver";
    Bool registered = ServerProvider::RegisterServer<HttpTcpArduinoServer>(serverId);
    
    if (registered) {
        Serial.println("[ServerProviderInit] Successfully registered HttpTcpArduinoServer");
        Serial.print("[ServerProviderInit] Total registered servers: ");
        Serial.println(ServerProvider::GetRegisteredCount());
    } else {
        Serial.println("[ServerProviderInit] WARNING: Failed to register HttpTcpArduinoServer (may already be registered)");
    }
    
    return registered;
#else
    std::cout << "[ServerProviderInit] Init() called (non-Arduino build)" << std::endl;
    std::cout << "[ServerProviderInit] No servers registered for desktop build" << std::endl;
    std::cout << "[ServerProviderInit] This file should be auto-generated by the build scripts." << std::endl;
    return false;
#endif
}

// Define static members outside the class (inline for header-only library)
inline Map<StdString, std::function<IServerPtr()>> ServerProvider::serverFactories_;
inline IServerPtr ServerProvider::defaultServerInstance_;

#ifdef ARDUINO
// Log when Init() is called during static initialization
bool isInit = []() -> bool {
    Serial.println("[ServerProviderInit] Static initialization - calling Init()...");
    bool result = Init();
    Serial.print("[ServerProviderInit] Init() returned: ");
    Serial.println(result ? "true" : "false");
    Serial.print("[ServerProviderInit] Registered server count after Init(): ");
    Serial.println(ServerProvider::GetRegisteredCount());
    return result;
}();
#else
// Log when Init() is called during static initialization
bool isInit = []() -> bool {
    std::cout << "[ServerProviderInit] Static initialization - calling Init()..." << std::endl;
    bool result = Init();
    std::cout << "[ServerProviderInit] Init() returned: " << (result ? "true" : "false") << std::endl;
    std::cout << "[ServerProviderInit] Registered server count after Init(): " << ServerProvider::GetRegisteredCount() << std::endl;
    return result;
}();
#endif

#endif // SERVERPROVIDERINIT_H

