#ifndef SERVERPROVIDERINIT_H
#define SERVERPROVIDERINIT_H

#include "ServerProvider.h"

#ifdef ARDUINO
#include <Arduino.h>
#else
#include <iostream>
#endif

/**
 * Initialize the provider with default server types
 * Registers HttpTcpServer with GUID "550e8400-e29b-41d4-a716-446655440000"
 * @return true if initialization was successful, false if server already registered
 */
inline Bool Init() {
#ifdef ARDUINO
    Serial.println("[ServerProviderInit] Init() called");
    Serial.println("[ServerProviderInit] WARNING: Init() returns false - no servers registered!");
    Serial.println("[ServerProviderInit] This file should be auto-generated by the build scripts.");
    Serial.println("[ServerProviderInit] Check if ServerProviderInit.h was generated correctly.");
#else
    std::cout << "[ServerProviderInit] Init() called" << std::endl;
    std::cout << "[ServerProviderInit] WARNING: Init() returns false - no servers registered!" << std::endl;
    std::cout << "[ServerProviderInit] This file should be auto-generated by the build scripts." << std::endl;
    std::cout << "[ServerProviderInit] Check if ServerProviderInit.h was generated correctly." << std::endl;
#endif
    return false;
}

// Define static members outside the class (inline for header-only library)
inline Map<StdString, std::function<IServerPtr()>> ServerProvider::serverFactories_;
inline IServerPtr ServerProvider::defaultServerInstance_;

#ifdef ARDUINO
// Log when Init() is called during static initialization
bool isInit = []() -> bool {
    Serial.println("[ServerProviderInit] Static initialization - calling Init()...");
    bool result = Init();
    Serial.print("[ServerProviderInit] Init() returned: ");
    Serial.println(result ? "true" : "false");
    Serial.print("[ServerProviderInit] Registered server count after Init(): ");
    Serial.println(ServerProvider::GetRegisteredCount());
    return result;
}();
#else
// Log when Init() is called during static initialization
bool isInit = []() -> bool {
    std::cout << "[ServerProviderInit] Static initialization - calling Init()..." << std::endl;
    bool result = Init();
    std::cout << "[ServerProviderInit] Init() returned: " << (result ? "true" : "false") << std::endl;
    std::cout << "[ServerProviderInit] Registered server count after Init(): " << ServerProvider::GetRegisteredCount() << std::endl;
    return result;
}();
#endif

#endif // SERVERPROVIDERINIT_H

